[project]
name = "trust-based-recommendation-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "ipywidgets>=8.1.6",
    "matplotlib>=3.5.3",
    "numpy>=1.21.6",
    "scipy>=1.7.3",
    "tqdm>=4.67.1",
]
